Add Class/Home work 8
FE38-Front-End/IvanDelendik pull request #10
Opened 2020-12-02 18:57 UTC by IvanDelendik

Add Home Work

2020-12-03 12:06 UTC, akhovbok requested changes

2020-12-03 12:06 UTC, akhovbok commented on Class Work 8/app1.js
> +let newLi;
какой смысл выносить эту перепенную за пределы обработчика события?

2020-12-03 12:06 UTC, akhovbok commented on Class Work 8/index8.html
> +    <script src="app1.js"></script>
атата app1.js

2020-12-03 12:06 UTC, akhovbok commented on Class Work 8/app1.js
> +let newUl;
а что у нас есть не new UL?

2020-12-06 12:46 UTC, IvanDelendik commented on Class Work 8/index8.html
> +    <script src="app1.js"></script>
Согласен, исправлюсь

2020-12-06 12:47 UTC, IvanDelendik commented on Class Work 8/app1.js
> +let newLi;
В принципе, нету. Сделал для улучшения читаемости

2020-12-06 12:48 UTC, IvanDelendik commented on Class Work 8/app1.js
> +let newUl;
Написал для упрощения читаемости.

2020-12-06 12:50 UTC, merged