Перемещиние оркужности вписанной в квадрат
FE38-Front-End/IvanDelendik pull request #11
Opened 2020-12-06 12:38 UTC by IvanDelendik

Решение задачи перемещения окружности внутри квадрата.

2020-12-24 09:31 UTC, akhovbok requested changes

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/Style.css
> +.input-param{
форматирование

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/Style.css
> +#square {
почему id?

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/index.html
> +  <input id="elem1" type="text" name="quantity" placeholder="Количество">
форматирование

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/app.js
> +butt.onclick = function () {
не понял откуда взялся butt мы нигде эту переменную не заводили

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/app.js
> +squareLenght = square.style.width = squareLenght + "px";
не вижу объявления переменной squareLenght

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/app.js
> +squareLenght = square.style.width = squareLenght + "px";
и не совсем понял что ты хочешь сделать этой строкой

2020-12-24 09:31 UTC, akhovbok commented on Class Work 9/app.js
> +const square = document.getElementById("square");
а где сохранение в стор? где дилегирование ивентов? где ввод параметров?

2020-12-26 13:49 UTC, IvanDelendik commented on Class Work 9/Style.css
> +.input-param{
Исправил

2020-12-26 13:49 UTC, IvanDelendik commented on Class Work 9/Style.css
> +#square {
Проще обращаться.

2020-12-26 13:50 UTC, IvanDelendik commented on Class Work 9/index.html
> +  <input id="elem1" type="text" name="quantity" placeholder="Количество">
исправил

2020-12-26 13:51 UTC, IvanDelendik commented on Class Work 9/app.js
> +butt.onclick = function () {
Это часть не касается задачи. Эксперименты проводил и не думал что они у тебя отобразятся. Пардон)

2020-12-26 13:51 UTC, IvanDelendik commented on Class Work 9/app.js
> +squareLenght = square.style.width = squareLenght + "px";
Это часть не касается задачи. Эксперименты проводил и не думал что они у тебя отобразятся. Пардон)

2020-12-28 19:23 UTC, IvanDelendik commented on Class Work 9/app.js
> +const square = document.getElementById("square");
Все исправил, в новом пуле

2021-01-30 08:30 UTC, akhovbok approved these changes

2021-01-30 08:30 UTC, akhovbok commented on Class Work 9/app.js
> +      topIndent = +(inputSaveSquare.value / 2 - inputSaveCircle.value / 2);
нет смысла ставить +

2021-01-30 08:30 UTC, akhovbok commented on Class Work 9/app.js
> +      buttonUp.disabled = true;
дублирование кода

2021-01-30 08:30 UTC, akhovbok commented on Class Work 9/app.js
> +    if (+inputSaveStep.value !== 0) {
inputSaveStep.value

2021-01-30 08:30 UTC, akhovbok commented on Class Work 9/app.js
> +const square = document.getElementById("square");
Много дублирования кода, имеет смысл выносить повторяющийся код в отдельные функции

2021-01-31 19:00 UTC, merged