Add Home Work 6
FE38-Front-End/IvanDelendik pull request #8
Opened 2020-11-26 12:30 UTC by IvanDelendik

Пока только считает количество труб внутри других. Остаточную площадь не учитываю.

2020-11-26 12:37 UTC, IvanDelendik commented
Согласен что коряво, но хотел саму суть донести. Пока интересней ее до решать, потом уже к оптимизации приступить)

2020-12-07 09:15 UTC, akhovbok requested changes

2020-12-07 09:15 UTC, akhovbok commented on Class Work 6/app2.js
> +  let dPipe = prompt(`Введите диаметр ${itaration}-ой трубы`);
А что если пользователь введет строку просто со своим именем например

2020-12-07 09:15 UTC, akhovbok commented on Class Work 6/app2.js
> +arrDPipe.sort((n1, n2) => n2 - n1).pop();
не понял для чего .pop()

2020-12-07 09:15 UTC, akhovbok commented on Class Work 6/app2.js
> +arrSPipe.push(Math.PI * Math.pow(arrDPipe[0] / 2, 2));
Возможно алгоритм рабочий но выглядит он совсем не понятным для других, в этом случае либо коментируют код либо разносят по отдельным функциям

2020-12-07 09:27 UTC, IvanDelendik commented on Class Work 6/app2.js
> +arrSPipe.push(Math.PI * Math.pow(arrDPipe[0] / 2, 2));
Честно говоря с начало было разнесено на отдельные итерации, а потом решил объединить все в одно

2020-12-28 19:25 UTC, IvanDelendik commented
Пока недошли руки дорешать. Вернуться позже. Задача про трубы

2020-12-28 19:25 UTC, merged